Port dmenu_run_hlwm to fish

diff --git a/herbstluftwm/dmenu_run_hlwm b/herbstluftwm/dmenu_run_hlwm
--- a/herbstluftwm/dmenu_run_hlwm
+++ b/herbstluftwm/dmenu_run_hlwm
@@ -1,46 +1,43 @@
-#!/usr/bin/env bash
+#!/usr/bin/env fish
 
-if ! command -v dmenu > /dev/null 2>/dev/null ; then
+if not command -sq dmenu
 	echo "Error: Requirement dmenu not found in your PATH." >&2
 	exit 1
-fi
+end
 
 # Get the currently active tag
-tag=$(herbstclient attr tags.focus.name)
+set -l tag (herbstclient attr tags.focus.name)
+set -l cmd
 
 # Redirect to dmenu_path if available
-if command -v dmenu_path > /dev/null 2>/dev/null ; then
-	selectedPath=$(dmenu_path | dmenu "$@")
+if command -sq dmenu_path
+    dmenu_path | dmenu $argv | read -a cmd
 
 # If we can find stest use the code from latest dmenu_path directly
-elif command -v stest > /dev/null 2>/dev/null ; then
-	cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
-	if [ -d "$cachedir" ]; then
-		cache=$cachedir/dmenu_run
-	else
-		cache=$HOME/.dmenu_cache # if no xdg dir, fall back to dotfile in ~
-	fi
-	IFS=:
-	if stest -dqr -n "$cache" $PATH; then
-		selectedPath=$(stest -flx $PATH | sort -u | tee "$cache" | dmenu "$@")
-	else
-		selectedPath=$(dmenu "$@" < "$cache")
-	fi
+else if command -sq stest
+	set -l cachedir $HOME/.cache
+    set -q XDG_CACHE_HOME; and set cachedir $XDG_CACHE_HOME
 
-# Both not found -> unable to continue
+    set -l cache $HOME/.dmenu_cache
+	test -d $cachedir; and set cache $cachedir/dmenu_run
+
+	if stest -dqr -n $cache $PATH
+		stest -flx $PATH | sort -u | tee $cache | dmenu $argv | read -a cmd
+	else
+		dmenu $argv < $cache | read -a cmd
+    end
 else
-	echo "Error: Requirements dmenu_path or stest not found in your PATH." >&2
+	echo "Error: Requires dmenu_path or stest in your PATH." >&2
 	exit 2
-fi
+end
 
 # Stop here if the user aborted
-[ -z $selectedPath ] && exit 0
+test -z "$cmd"; and exit 0
 
 # Move next window from this process to this tag. Prepend the rule so
 # that it may be overwritten by existing custom rules e.g. in the
 # autostart. Also set a maximum age for this rule of 60 seconds and
 # mark it as one-time-only rule.
-herbstclient rule prepend maxage="60" pid="$$" tag="$tag" once
+herbstclient rule prepend maxage=60 pid=(echo -n %self) tag=$tag once
 
-exec $selectedPath
-
+exec env $cmd
